name: ðŸš€ Deploy website on push
on: 
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy Program
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v2
    
    - name: ðŸ“‚ Sync GitHub & Server Files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: sg2plzcpnl486124.prod.sin2.secureserver.net
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
